name: otbr
services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - '.env'
    networks:
      - canary-net
    ports:
      - '$MYSQL_PORT:3306'
    volumes:
      - 'db-volume:/var/lib/mysql'
      - ../schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 10

  server:
    # cpuset: "0-4"
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: prod
      args:
        VCPKG_BINARY_SOURCES: ${VCPKG_BINARY_SOURCES:-}
    restart: unless-stopped
    env_file:
      - '.env'
    environment:
      - OT_DB_HOST=database
      - OT_DB_PORT=3306
      - OT_DB_USER=canary
      - OT_DB_PASSWORD=canary
      - OT_DB_DATABASE=otservbr-global
      - OT_SERVER_TEST_ACCOUNTS=true
    networks:
      - canary-net
    ports:
      - '$gameProtocolPort:$gameProtocolPort'
      - '$statusProtocolPort:$statusProtocolPort'
    volumes:
      - '../:/srv/canary'
    depends_on:
      database:
        condition: service_healthy

  login:
    image: opentibiabr/login-server:latest
    restart: unless-stopped
    ports:
      - '$LOGIN_HTTP_PORT:$LOGIN_HTTP_PORT'
      - '$LOGIN_GRPC_PORT:$LOGIN_GRPC_PORT'
    env_file:
      - '.env'
    networks:
      - canary-net
    depends_on:
      database:
        condition: service_healthy
      server:
        condition: service_started

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=$MYSQL_ROOT_PASSWORD
    networks:
      - canary-net
    depends_on:
      database:
        condition: service_healthy

volumes:
  db-volume:


networks:
  canary-net:
    driver: bridge

# secrets:
#   github_token:
#     file: ./github_token.txt
